# Generated by Django 2.1.5 on 2019-01-21 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 19, 38, 4, 146160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 19, 38, 4, 146182, tzinfo=utc)),
        ),
    ]
